runtime: python27
api_version: 1
threadsafe: true
service: agent-server

handlers:
- url: /.*
  script: app.app

libraries:
- name: ssl
  version: latest

# NEED TO SET A STANDARD FOR NAMING ENV VARS
env_variables:
  COWBULL_URL: "http://cowbull-test-project.appspot.com/v1/{}"
  COWBULL_SERVER: "http://cowbull-test-project.appspot.com/v1/{}"
  COWBULL_PORT: 80
  LOGGING_LEVEL: 10
